### ISSUE TITLE
Unable to add item to cart

### ISSUE THREAD

**Issue by dmhumph** [redhatdemocentral/rhcs-coolstore-demo#3]
When running in CDK there is an error when an item is added to cart.  The following error is found in the container log:

15:04:41,753 SEVERE [com.vaadin.server.DefaultErrorHandler] (http-0.0.0.0:8080-7) : javax.ejb.NoSuchEJBException: JBAS016055: EJB has been removed
	at org.jboss.as.weld.ejb.StatefulSessionObjectReferenceImpl.getBusinessObject(StatefulSessionObjectReferenceImpl.java:123) [jboss-as-weld-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:113) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at com.redhat.coolstore.service.ShoppingCartService$998405650$Proxy$_$$_Weld$Proxy$.priceShoppingCart(ShoppingCartService$998405650$Proxy$_$$_Weld$Proxy$.java) [classes:]
	at com.redhat.coolstore.web.ui.ShoppingCartView.updateDatasource(ShoppingCartView.java:102) [classes:]
	at com.redhat.coolstore.web.ui.ShoppingCartView.updateShoppingCart(ShoppingCartView.java:114) [classes:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_71]
	at org.jboss.weld.util.reflection.SecureReflections$13.work(SecureReflections.java:267) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:52) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInvocation(SecureReflectionAccess.java:137) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.util.reflection.SecureReflections.invoke(SecureReflections.java:263) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.introspector.jlr.WeldMethodImpl.invokeOnInstance(WeldMethodImpl.java:164) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.introspector.ForwardingWeldMethod.invokeOnInstance(ForwardingWeldMethod.java:51) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:163) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:245) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:233) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:213) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:117) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.event.TransactionalObserverNotifier.notifyObserver(TransactionalObserverNotifier.java:44) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:85) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:80) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:69) [weld-core-1.1.33.Final-redhat-1.jar:1.1.33.Final-redhat-1]
	at com.redhat.coolstore.web.ui.ProductsView.buttonClick(ProductsView.java:168) [classes:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_71]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.ui.Button.fireClick(Button.java:377) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.ui.Button$1.click(Button.java:54) [vaadin-server-7.7.2.jar:7.7.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_71]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:435) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:407) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1422) [vaadin-server-7.7.2.jar:7.7.2]
	at com.vaadin.cdi.server.VaadinCDIServletService.handleRequest(VaadinCDIServletService.java:92) [vaadin-cdi-1.0.3.jar:1.0.3]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:370) [vaadin-server-7.7.2.jar:7.7.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-2.jar:1.0.2.Final-redhat-2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.7.Final-redhat-3.jar:7.5.7.Final-redhat-3]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:419) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:654) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.15.Final-redhat-1.jar:7.5.15.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_71]

**Comment by eschabell** [comment]
I just tested this with the latest CDK installation demo and CoolStore. My steps that worked without errors:

1. install cdk-install-demo
2. install rhcs-coolstore-demo
3. login OSE 10.1.2.2 to check pod deployed and BRMS start finished
4. login BRMS Business central: http://rhcs-coolstore-demo.10.1.2.2.xip.io/business-central
5. build and deploy coolstore project version 2.0.0
6. view logs on container pod, watch build complete without errors:

12:46:37,118 INFO [org.drools.compiler.kie.builder.impl.KieRepositoryImpl] (Timer-1) KieModule was added: ZipKieModule[releaseId=com.redhat:coolstore:2.0.0,file=/opt/jboss/.m2/repository/com/redhat/coolstore/2.0.0/coolstore-2.0.0.jar]

7. open web app: http://rhcs-coolstore-demo.10.1.2.2.xip.io/brms-coolstore-demo
8. see logs for KieScanner picking up the 2.0.0 deployment:

12:46:37,128 INFO [org.kie.api.builder.KieScanner] (Timer-1) The following artifacts have been updated: {com.redhat:coolstore:2.0.0=com.redhat:coolstore:jar:2.0.0}

9. add item from under $25, see post cost set to $2.99.
10. go back to business central and update decision table rule entry for 0-25 placing shipping at $22.99, save, build and deploy project while bumping version to 2.0.1
11. back in container pod log look for build and KieScanner from web app picking up the changed rules:

12:48:11,211 INFO [org.drools.compiler.kie.builder.impl.KieRepositoryImpl] (http-0.0.0.0:8080-3) KieModule was added: MemoryKieModule[releaseId=com.redhat:coolstore:2.0.1]
12:48:15,999 INFO  [org.drools.compiler.kie.builder.impl.KieRepositoryImpl] (Timer-1) KieModule was added: ZipKieModule[releaseId=com.redhat:coolstore:2.0.1,file=/opt/jboss/.m2/repository/com/redhat/coolstore/2.0.1/coolstore-2.0.1.jar]
12:48:16,101 INFO [org.kie.api.builder.KieScanner] (Timer-1) The following artifacts have been updated: {com.redhat:coolstore:2.0.0=com.redhat:coolstore:jar:2.0.1}

12. Now back in web app, clear out previous data (with button), add item under $25 and watch pricing for shipping be set to new $22.99 value.

Maybe you failed to use the right order? Sometimes the web app is started by users and tried without deploying rules first...gives strange behavior.
